#!/bin/sh
#
# S80onvif        Startup script for the Onvif server
#
# processname: onvif-server
# config: /etc/generic-onvif-server/confs
# pidfile: /var/run/onvif.pid

DAEMON="onvif-server"
PIDFILE="/var/run/$DAEMON.pid"
IFACE=eth0
IP=$(/sbin/ifconfig $IFACE | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')
ONVIF_ARGS="--xaddr $IP"

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

# BusyBox' syslogd does not create a pidfile, so pass "-n" in the command line
# and use "-m" to instruct start-stop-daemon to create one.
start() {
	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/bin/$DAEMON" -- $ONVIF_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
